### ISSUE TITLE
Won't compile on nginx-1.12.2

### ISSUE THREAD

**Issue by ghost** [nginx-modules/ngx_http_hmac_secure_link_module#3]
Using nginx-1.12.2 I get the following compile errors:

```
/path/to/nginx/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c: In function ‘ngx_http_secure_link_variable’:
/path/to/nginx/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:160:31: error: format ‘%d’ expects argument of type ‘int *’, but argument 3 has type ‘ngx_int_t * {aka long int *}’ [-Werror=format=]
         if (sscanf((char *)p, "%d-%d-%dT%d:%d:%d%c%d:%d",
                               ^
/path/to/nginx/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:160:31: error: format ‘%d’ expects argument of type ‘int *’, but argument 4 has type ‘ngx_int_t * {aka long int *}’ [-Werror=format=]
/path/to/nginx/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:160:31: error: format ‘%d’ expects argument of type ‘int *’, but argument 5 has type ‘ngx_int_t * {aka long int *}’ [-Werror=format=]
/path/to/nginx/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:160:31: error: format ‘%d’ expects argument of type ‘int *’, but argument 6 has type ‘ngx_int_t * {aka long int *}’ [-Werror=format=]
/path/to/nginx/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:160:31: error: format ‘%d’ expects argument of type ‘int *’, but argument 7 has type ‘ngx_int_t * {aka long int *}’ [-Werror=format=]
/path/to/nginx/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:160:31: error: format ‘%d’ expects argument of type ‘int *’, but argument 8 has type ‘ngx_int_t * {aka long int *}’ [-Werror=format=]
/path/to/nginx/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:160:31: error: format ‘%d’ expects argument of type ‘int *’, but argument 10 has type ‘ngx_int_t * {aka long int *}’ [-Werror=format=]
/path/to/nginx/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:160:31: error: format ‘%d’ expects argument of type ‘int *’, but argument 11 has type ‘ngx_int_t * {aka long int *}’ [-Werror=format=]
/path/to/nginx/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c: In function ‘ngx_http_secure_link_token_variable’:
/path/to/nginx/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:331:71: error: passing argument 7 of ‘HMAC’ from incompatible pointer type [-Werror=incompatible-pointer-types]
     HMAC(evp_md, key.data, key.len, value.data, value.len, hmac.data, &hmac.len);
                                                                       ^
In file included from /path/to/nginx/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:7:0:
/usr/include/openssl/hmac.h:98:16: note: expected ‘unsigned int *’ but argument is of type ‘size_t * {aka long unsigned int *}’
 unsigned char *HMAC(const EVP_MD *evp_md, const void *key, int key_len,
                ^
cc1: all warnings being treated as errors
objs/Makefile:1167: recipe for target 'objs/addon/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.o' failed
make[1]: *** [objs/addon/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.o] Error 1
make[1]: Leaving directory '/path/to/nginx/nginx-1.12.2'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by ghost** [comment]
Have you tried the "fix"? It doesn't work. Can you please reopen?
